<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="plugin:/platform/no.hal.eclipsky.services.workspace/model/workspace-services.ecore"
    nsPrefix="ws">
  <eClassifiers xsi:type="ecore:EClass" name="AbstractService" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requestTime" eType="#//ETimestamp"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="responseTime" eType="#//ETimestamp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ETimestamp" instanceClassName="long"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProjectService" eSuperTypes="#//AbstractService">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="projectRef" eType="#//EProjectRef"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceService" eSuperTypes="#//AbstractService">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resourceRef" eType="#//EResourceRef"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EProjectRef" instanceClassName="no.hal.eclipsky.services.common.ProjectRef"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EResourceRef" instanceClassName="no.hal.eclipsky.services.common.ResourceRef"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnsureProjectService" eSuperTypes="#//ProjectService">
    <eStructuralFeatures xsi:type="ecore:EReference" name="emfs" eType="ecore:EClass ../../no.hal.emfs/model/emfs.ecore#//EmfsResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProjectListService" eSuperTypes="#//AbstractService">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="namePattern" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responseOptions" eType="#//ProjectResponseOptions"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="projects" upperBound="-1"
        eType="#//ProjectInfo" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProjectResponseOptions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="includeResources" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourceResponseOptions"
        eType="#//ResourceResponseOptions" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceResponseOptions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="includeContents" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="includeMarkers" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProjectInfo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="projectRef" eType="#//EProjectRef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
        eType="#//ResourceInfo" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceInfo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resourceRef" eType="#//EResourceRef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" eType="ecore:EClass ../../no.hal.emfs/model/emfs.ecore#//AbstractStringContentProvider"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="markers" upperBound="-1"
        eType="#//SourceFileMarker" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SourceEditorService" eSuperTypes="#//ResourceService"/>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceInfoService">
    <eStructuralFeatures xsi:type="ecore:EReference" name="responseOptions" eType="#//ResourceResponseOptions"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resource" eType="#//ResourceInfo"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RefreshEditorService" eSuperTypes="#//SourceEditorService">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resource" eType="#//ResourceInfo"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MarkersEditorService" eSuperTypes="#//SourceEditorService">
    <eStructuralFeatures xsi:type="ecore:EReference" name="markers" eType="#//ResourceInfo"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateEditorService" eSuperTypes="#//MarkersEditorService">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" eType="ecore:EClass ../../no.hal.emfs/model/emfs.ecore#//AbstractStringContentProvider"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FileMarker" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="severity" eType="#//SeverityKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SourceFileMarker" eSuperTypes="#//FileMarker">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="start" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompletionEditorService" eSuperTypes="#//SourceEditorService">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="proposals" upperBound="-1"
        eType="#//CompletionProposal" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompletionProposal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="score" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CloseEditorService" eSuperTypes="#//ResourceService"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionService" eSuperTypes="#//ResourceService">
    <eStructuralFeatures xsi:type="ecore:EReference" name="result" eType="#//ExecutionResult"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionResult">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sysout" eType="ecore:EClass ../../no.hal.emfs/model/emfs.ecore#//AbstractStringContents"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="syserr" eType="ecore:EClass ../../no.hal.emfs/model/emfs.ecore#//AbstractStringContents"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exceptionLocation" eType="#//SourceFileMarker"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RunEditorService" eSuperTypes="#//ExecutionService"/>
  <eClassifiers xsi:type="ecore:EClass" name="TestEditorService" eSuperTypes="#//ExecutionService"/>
  <eClassifiers xsi:type="ecore:EClass" name="TestResult" eSuperTypes="#//ExecutionResult">
    <eStructuralFeatures xsi:type="ecore:EReference" name="results" upperBound="-1"
        eType="#//TestCaseResult" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestCaseResult">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//ResultKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exception" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ResultKind">
    <eLiterals name="UNKNOWN" literal="UNKNOWN"/>
    <eLiterals name="SUCCESS" value="1" literal="SUCCESS"/>
    <eLiterals name="FAILURE" value="2" literal="FAILURE"/>
    <eLiterals name="ERROR" value="3" literal="ERROR"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SeverityKind">
    <eLiterals name="UNKNOWN" literal="UNKNOWN"/>
    <eLiterals name="OK" value="1" literal="OK"/>
    <eLiterals name="INFO" value="2" literal="INFO"/>
    <eLiterals name="WARNING" value="3" literal="WARNING"/>
    <eLiterals name="ERROR" value="4" literal="ERROR"/>
  </eClassifiers>
</ecore:EPackage>
